#!/usr/bin/env bash

set -e

(
 cd cdk
 ./script/ci
)


sbt "set version := \"$BUILD_NUMBER\"" clean scalafmtCheckAll compile test debian:packageBin Docker/publishLocal

mkdir -p dist
mv target/*.deb "dist/amiable-${BUILD_NUMBER}.deb"
