# Find full documentation here https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: CI

on:
  pull_request:

  workflow_dispatch:

  push:
    branches:
      - "main"
jobs:
  CI:
    runs-on: ubuntu-latest

    # See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      # required by aws-actions/configure-aws-credentials
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      # Setup AWS credentials to enable uploading to S3 for Riff-Raff.
      # See https://github.com/aws-actions/configure-aws-credentials
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1

      # Setup Node, checking common Node config files to determine the version of Node to use.
      # Configuring caching is also recommended.
      # See https://github.com/guardian/actions-setup-node
      - name: Setup Node
        uses: guardian/actions-setup-node@v2.4.1

      # See https://github.com/actions/setup-java
      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'sbt'

      # See https://github.com/github/scripts-to-rule-them-all
      - name: Run script/ci
        run: |
          LAST_TEAMCITY_BUILD=1007
          export GITHUB_RUN_NUMBER=$(( $GITHUB_RUN_NUMBER + $LAST_TEAMCITY_BUILD ))
          ./script/ci
