# Find full documentation here https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: CI

on:
  pull_request:

  workflow_dispatch:

  push:
    branches:
      - "main"
jobs:
  CI:
    runs-on: ubuntu-latest

    # See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      contents: read

      # These permissions are required by guardian/actions-riff-raff...
      id-token: write # ...to exchange an OIDC JWT ID token for AWS credentials
      pull-requests: write #...to comment on PRs
    steps:
      - uses: actions/checkout@v4.1.1

      # Setup Node, checking common Node config files to determine the version of Node to use.
      # Configuring caching is also recommended.
      # See https://github.com/guardian/actions-setup-node
      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'cdk/package-lock.json'

      # See https://github.com/actions/setup-java
      - name: Setup Java 11
        uses: actions/setup-java@v4.1.0
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: 'sbt'

      # See https://github.com/github/scripts-to-rule-them-all
      - name: Run script/ci
        run: ./script/ci

      - name: Upload to riff-raff
        uses: guardian/actions-riff-raff@v4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          buildNumberOffset: 1007
          projectName: tools::amiable
          configPath: cdk/cdk.out/riff-raff.yaml
          contentDirectories: |
            cdk.out:
              - cdk/cdk.out
            amiable:
              - amiable.deb
