# Part of the Scala Steward implementation on this repository, this workflow will open a PR from dependency-updates_1 to main once a month.
# The effect is we bump dependencies once a month, in one mega PR.

name: Aggregate dependency updates

on:
  schedule:
    - cron: "35 10 1 * *"
  # Provide support for manually triggering the workflow via GitHub.
  workflow_dispatch:

jobs:
  pr-tracking-branch:
    name: Open a PR from dependency-updates targeting main
    uses: guardian/.github/.github/workflows/pr-batching_pr-tracking-branch-to-default.yml@v1.0.1
    with:
      BRANCH: dependency-updates_1
